ci(repo): migrate to github actions.
tu-graz-library/invenio-marc21 pull request #11
Opened 2020-12-07 07:31 UTC by philippgualdi

2020-12-09 08:54 UTC, mb-wali commented on .github/workflows/tests.yml
> +          requirements-level: [min, pypi]
Seeing the previous ```travis.yml``` file - this module needs some services - such as ES, DB in order to run the tests.
consider adding them in the github action yml file.

2020-12-09 08:56 UTC, mb-wali commented on setup.py
> +    "SQLAlchemy-Continuum>=1.3.11",
what was the reason for changing these dependencies- cannot find anything in the description or in the commits.

2020-12-09 09:03 UTC, mb-wali requested changes
### Request changes
1. add ES, DB services to the GitHub action .yml file. See [reference](https://github.com/inveniosoftware/invenio-rdm-records/blob/95e8bbb3f5d3cec41e28e425622179c05573bd69/.github/workflows/tests.yml#L26)
2. update files ```run-tests.sh``` , ```pytest.ini```, ```CONTRIBUTING.rst``` and  ```README.rst``.  See [reference](https://github.com/tu-graz-library/invenio-theme-tugraz/pull/119)

2020-12-10 06:13 UTC, philippgualdi commented on .github/workflows/tests.yml
> +          requirements-level: [min, pypi]
On travis build we had the issue in the run-tests.sh https://github.com/tu-graz-library/invenio-marc21/blob/master/run-tests.sh#L10 docker-services-cli pulls already the elasticsearch container. 

Travis build log: https://travis-ci.com/github/tu-graz-library/invenio-marc21/jobs/449653590 on line 650

2020-12-10 06:20 UTC, philippgualdi commented on setup.py
> +    "SQLAlchemy-Continuum>=1.3.11",
In the test/conftest.py we import InvenioIndexer which raises the  ModuleNotFoundError: No module named 'invenio_search' found, so I added explicit to install the packages for tests.

2020-12-10 08:26 UTC, philippgualdi commented
I'll change the build script according to the  inveniosoftware  policy.

2020-12-10 10:11 UTC, mb-wali commented on .github/workflows/tests.yml
> +          requirements-level: [min, pypi]
This was the issue from travis-ci - if you run again the job this will disappear.

2020-12-10 10:12 UTC, mb-wali approved these changes

2020-12-10 11:09 UTC, merged