Fix build with travis CI
tu-graz-library/invenio-marc21 pull request #7
Opened 2020-11-09 15:41 UTC by philippgualdi

Update setup and travis CI Build.

2020-11-13 09:34 UTC, mb-wali requested changes

2020-11-13 09:34 UTC, mb-wali commented on setup.py
>      'pytest>=4.6.4,<5.0.0',
```suggestion
    "pytest-invenio>=1.4.0",
```
Also - remove these packages listed bellow from ```tests_require =[]```
```
'check-manifest>=0.25',
'coverage>=4.5.3',
'isort>=4.2.2',
'mock>=1.3.0',
'pydocstyle>=3.0.0',
'pytest-cov>=2.7.1',
'pytest-pep8>=1.0.6',
```
The reason for removing these packages is that we are installing the ```"pytest-invenio>=1.4.0",``` package which is installing these packages to keep the tests packages in one place. See [HERE](https://github.com/inveniosoftware/pytest-invenio/blob/798eaa4140dcdfe6e2cb51338915701a993545ee/setup.py#L48)

2020-11-13 09:34 UTC, mb-wali commented on setup.py
>          'Development Status :: 5 - Production/Stable',
```suggestion
       "Development Status :: 3 - Alpha",
```

Reason: the status for development is Alpha.

2020-11-13 10:30 UTC, philippgualdi commented on setup.py
>      'pytest>=4.6.4,<5.0.0',
The dependency pytest-pep8 is not satisfied in pytest-invenio. Should it be removed from run-tests.sh?

2020-11-13 10:37 UTC, mb-wali commented on setup.py
>      'pytest>=4.6.4,<5.0.0',
yes you can remove this package, and modify your ```pytest.ini``` file, Check [here](https://github.com/tu-graz-library/invenio-theme-tugraz/blob/master/pytest.ini) for a reference.

2020-11-16 08:23 UTC, mb-wali approved these changes

2020-11-16 08:25 UTC, mb-wali approved these changes

2020-11-16 08:29 UTC, mb-wali commented
@philippgualdi quick check befor merging. agree if the statement below is correct.
This PR closes #1 and #5.

2020-11-16 12:44 UTC, philippgualdi commented
Yes issue #1 and #5 can be closed.

2020-11-16 12:51 UTC, merged